package javaTimeAll;

import java.time.LocalDateTime;
import java.util.Scanner;

class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		boolean endProgram = false;
		boolean hostExist = false;
		boolean inputRecordMatch = false;
		boolean visitorExist = false;
		boolean doneSearch = false;
		boolean cancelCode = false;
		boolean doneCodeLookUp = false;
		boolean doneVisitorLookUp = false;
		boolean previousCodeFound = false;
		boolean hostHasCode = false; 

//		Welcome message
		System.out.println("Welcome to the Visitor Access Management System!");
		System.out.println();
		while (endProgram == false) {
//			Prompt user to select role
			System.out.println("Please select your role: ");
			System.out.println("Host: H");
			System.out.println("Visitor: V");
			System.out.println("Admin: A");
			String role = sc.nextLine().toUpperCase();
//			HOST
			if (role.equals("H")) {
				System.out.println("Hi, Host.");
				System.out.println("Please enter your ID number: ");
				String hostId = sc.nextLine().toUpperCase();
//				Find if the id exists in the current hostArrayList
				while (hostExist == false) {
					for (int i = 0; i < SharedData.hostArrayList.size(); i++) {
						Host hostObject = SharedData.hostArrayList.get(i);
						if (hostId.equals(hostObject.id)) {
							hostExist = true;
							System.out.println("Welcome back!");
						}
					}
//				If the id doesnt exist in the current hostArrayList, Create host
					if (hostExist == false) {
//						System.out.println("Please contact Admin to register your host account.");
						System.out.println("Please enter your address (e.g. 12B): ");
						String hostAddress = sc.nextLine().toUpperCase();
						SharedData.addHost(hostId, hostAddress);
						hostExist = true;
//						endProgram = true;
					}
				}
//				Host actions
				System.out.println("What would you like to do?");
//				Determine if the host has a code in codeArrayList
				for (int i = 0; i < SharedData.codeArrayList.size(); i++) {
					Code codeObject = SharedData.codeArrayList.get(i);
					if (codeObject.hostId.equals(hostId)) {
						hostHasCode = true;
						break;
					} 
				}
				if (SharedData.codeArrayList.size() == 0 || hostHasCode == false ) {
//					If the host does not have a valid code in codeArrayList, prompt host to generate a new code 
					System.out.println("Generate new code: G");
				} else {
//					If the host has a valid code in codeArrayList, prompt host to generate a new code or cancel an active code
					System.out.println("Generate new code: G");
					System.out.println("Cancel code: C");
				}
				String cancelGenerate = sc.nextLine().toUpperCase();
//				GENERATE NEW CODE
				if (cancelGenerate.equals("G")) {
					System.out.println("Please enter the visitor's ID number: ");
					String visitorId = sc.nextLine().toUpperCase();
					for (int i = 0; i < SharedData.hostArrayList.size(); i++) {
						Host hostObject = SharedData.hostArrayList.get(i);
						if (hostId.equals(hostObject.id)) {
							while (previousCodeFound == false && SharedData.codeArrayList.size() > 0) {
								for (int j = 0; j < SharedData.codeArrayList.size(); j++) {
									Code codeObject = SharedData.codeArrayList.get(j);
//									Invalidate any valid code previously generated by the host for the visitor
									if (codeObject.visitorId.equals(visitorId) && codeObject.used == false && codeObject.isValid && codeObject.hostAddress.equals(hostObject.address)) {
										codeObject.invalidate();
										previousCodeFound = true;
										break;
									} else if (j == SharedData.codeArrayList.size() - 1) {
										previousCodeFound = true;
										break;
									}
								}
							}
//							generate code
							hostObject.generateCode(visitorId);
							SharedData.addCode(hostObject.nextCode, hostObject.address, hostObject.nextVisitorId, hostObject.generationDatetime, hostObject.id);
						}
					}
//                CANCEL CODE
				} else if (cancelGenerate.equals("C") && SharedData.codeArrayList.size() > 0) {
					System.out.println("Please enter the code you would like to cancel: ");
					String codeCancel = sc.nextLine();
					while (cancelCode == false && doneCodeLookUp == false) {
						for (int i = 0; i < SharedData.codeArrayList.size(); i++) {
							Code codeObject = SharedData.codeArrayList.get(i);
							if (codeCancel.equals(codeObject.code) && hostId.equals(codeObject.hostId)) {
//								Invalidate code
								codeObject.invalidate();
								cancelCode = true;
								doneCodeLookUp = true;
								break;
							}
//							Handle wrong code input
							if (i == SharedData.codeArrayList.size() - 1 && cancelCode == false) {
								System.out.println("No such code found");
								doneCodeLookUp = true;
								break;
							}
						}
					}

				} 
//				Handle input != C or G
				else {
					System.out.println("Action unavailable");
				}
			} 
//			VISITOR
			else if (role.equals("V")) {
				System.out.println("Hi, Visitor.");
				System.out.println("Please enter your ID number: ");
				String visitorId = sc.nextLine().toUpperCase();
				System.out.println("Please enter your host's address: ");
				String address = sc.nextLine().toUpperCase();
				System.out.println("Please enter your 6-digit code: ");
				String code = sc.nextLine().toUpperCase();
				LocalDateTime inputTime = LocalDateTime.now();
//				Find match
				while (doneSearch == false) {
					for (int i = 0; i < SharedData.codeArrayList.size(); i++) {
						Code codeObject = SharedData.codeArrayList.get(i);
//						Only when all of the following conditions are met:
//						Condition #1: input time within 3 hours after codeObject.generationDateTime
//						Condition #2: visitorId input matches codeObject.visitorId
//						Condition #3: address input matches codeObject.hostAddress
//						Condition #4: code input matches codeObject.code
//						Condition #5: codeObject.isValid == true
//						Condition #6: codeObject.used == false
						if (inputTime.compareTo(codeObject.generationDateTime.plusHours(3)) == -1 && visitorId.equals(codeObject.visitorId) && address.equals(codeObject.hostAddress) && code.equals(codeObject.code) && codeObject.isValid && codeObject.used == false) {
							inputRecordMatch = true;
//							Set codeObject.used to true (Grant access)
							codeObject.used = true;
							while (visitorExist == false && inputRecordMatch == true) {
//								Find visitor
								for (int j = 0; j < SharedData.visitorArrayList.size(); j++) {
									Visitor visitorObject = SharedData.visitorArrayList.get(j);
									if (visitorId.equals(visitorObject.id)) {
										System.out.println("Visitor already exists.");
										visitorExist = true;
										doneSearch = true;
										break;
									}
								}
//								If not found, create visitor
								while (visitorExist == false) {
									SharedData.addVisitor(visitorId);
									visitorExist = true;
									doneSearch = true;
									break;
								}
							}
						} 
//						If any of the above condition is not met, deny access
						else if (i == SharedData.codeArrayList.size() - 1 && inputRecordMatch == false) {
							doneSearch = true;
							doneVisitorLookUp = true;
							System.out.println("Access denied.");
							break;
						}						
					}
				}
//				Create access
				while (doneVisitorLookUp == false) {
					for (int j = 0; j < SharedData.visitorArrayList.size(); j++) {
						Visitor visitorObject = SharedData.visitorArrayList.get(j);
						if (visitorId.equals(visitorObject.id)) {
							visitorObject.setExpectedAddress(address);
							visitorObject.setExpectedCode(code);
							visitorObject.grantAccess(inputTime);
							SharedData.addAccess(visitorObject.expectedAddress, visitorObject.id, visitorObject.expectedCode, visitorObject.accessDateTime);
							doneVisitorLookUp = true;
							break;
						}
					}
				}
				
				

				
				
			} else if ((role.equals("A"))) {
				System.out.println("Hi, Admin.");
				System.out.println("What would you like to do?");
				System.out.println("Add new Host: ADD");
				if (SharedData.hostArrayList.size() > 0) {
					System.out.println("Remove Host: DEL");
					System.out.println("Show all Hosts: ALLH");
				}
				if (SharedData.visitorArrayList.size() > 0) {
					System.out.println("Show all Visitors: ALLV");
				}
				if (SharedData.accessArrayList.size() > 0) {
					System.out.println("Show all Access: ALLA");
				}
				String adminAction = sc.nextLine().toUpperCase();
				if (adminAction.equals("ADD")) {
					System.out.println("Please enter the host's ID number: ");
					String hostId = sc.nextLine().toUpperCase();
					System.out.println("Please enter the host's address (e.g. 12B): ");
					String hostAddress = sc.nextLine().toUpperCase();
					SharedData.addHost(hostId, hostAddress);
				} else if (adminAction.equals("DEL") && SharedData.hostArrayList.size() > 0) {
					System.out.println("Please enter the host's ID number: ");
					String hostId = sc.nextLine().toUpperCase();
					SharedData.removeHost(hostId);
				} else if (adminAction.equals("ALLH") && SharedData.hostArrayList.size() > 0) {
					SharedData.showAllHost();
				} else if (adminAction.equals("ALLV") && SharedData.codeArrayList.size() > 0) {
					SharedData.showAllVisitor();
				} else if (adminAction.equals("ALLA") && SharedData.accessArrayList.size() > 0) {
					SharedData.showAllAccess();
				} else {
					System.out.println("Action unavailable");
				}
			
			} else {
				System.out.println("Maintenance");
			}
			
			System.out.println("Would you like to close the program?");
			System.out.println("Yes: Y");
			System.out.println("No: N");
			String endOption = sc.nextLine().toUpperCase();
			
			if (endOption.equals("Y")) {
				endProgram = true;
			} else {
				endProgram = false;
			    hostExist = false;
			    inputRecordMatch = false;
			    visitorExist = false;
			    doneSearch = false;
			    cancelCode = false;
			    doneCodeLookUp = false;
			    doneVisitorLookUp = false;
			    previousCodeFound = false;
			    hostHasCode = false;
			}
		}

	}

}


